// @ts-nocheck
export const SET_CURRENT_ACL = "SET_CURRENT_ACL"
export const SET_IS_DETAIL_VIEW = "SET_IS_DETAIL_VIEW"
export const SET_IS_PERMIT_DETAIL_VIEW = "SET_IS_PERMIT_DETAIL_VIEW"
export const SET_IS_SECURE_VIEW = "SET_IS_SECURE_VIEW"
export const SET_IS_VIEW_FROM_LIST = "SET_IS_VIEW_FROM_LIST"
