// @ts-nocheck
export const TABS = [
  {
    icon: "User",
    ftype: 1,
    id: "my",
    pid: "0",
    text: "My",
    iconCls: "x-tree-icon-parent",
    leaf: false,
    author: "PhuongDofu1",
    authorId: "12",
    rootUserId: "12",
    sync: null,
    star: false,
    notify: false,
    access: {
      download: true,
      upload: true,
      edit: true,
      remove: true,
      read: true,
      share: true,
      guest: true,
    },
    flag: [""],
  },
  {
    icon: "UploadCloud",
    ftype: 0,
    id: "sync",
    pid: "33",
    text: "CloudFolder",
    iconCls: "x-tree-icon-parent-sync",
    leaf: false,
    author: null,
    authorId: "0",
    rootUserId: "12",
    sync: true,
    star: false,
    notify: false,
    access: {
      download: true,
      upload: true,
      edit: false,
      remove: false,
      read: true,
      share: true,
      guest: true,
    },
    flag: [""],
  },
  {
    icon: "Users",
    ftype: 1,
    id: "org",
    pid: "",
    text: "Company",
    iconCls: "x-tree-icon-parent",
    leaf: false,
    author: "",
    authorId: 0,
    rootUserId: 0,
    sync: false,
    star: false,
    notify: false,
    access: {
      download: false,
      upload: false,
      edit: false,
      remove: false,
      read: false,
      share: false,
      guest: false,
    },
    flag: [""],
  },
  {
    icon: "Share2",
    ftype: 1,
    id: "share",
    pid: "",
    text: "Shared",
    iconCls: "x-tree-icon-parent",
    leaf: true,
    author: "",
    authorId: 0,
    rootUserId: 0,
    sync: false,
    star: false,
    notify: false,
    access: {
      download: false,
      upload: false,
      edit: false,
      remove: false,
      read: false,
      share: false,
      guest: false,
    },
    flag: [""],
  },
  {
    icon: "File",
    ftype: 1,
    id: 0,
    pid: "",
    text: "All",
    iconCls: "x-tree-icon-parent",
    leaf: true,
    author: "",
    authorId: 0,
    rootUserId: 0,
    sync: false,
    star: false,
    notify: false,
    access: {
      download: false,
      upload: false,
      edit: false,
      remove: false,
      read: false,
      share: false,
      guest: false,
    },
    flag: [""],
  },
  {
    id: -1,
    icon: "Upload",
    text: "Upload",
  },
];

export const DATA_CLOUDDISK = {
  total: 12,
  files: [
    {
      id: "103921",
      pid: "39227",
      name: "Folder 1",
      text: "Folder 1",
      size: "382352",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998520",
      type: "dir",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "folder",
      ext2: "folder",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: true,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "1", file: "7", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103922",
      pid: "39227",
      name: "Folder 2",
      text: "Folder 2",
      size: "0",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998531",
      type: "dir",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "folder",
      ext2: "folder",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: true,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103924",
      pid: "39227",
      name: "Folder 3",
      text: "Folder 3",
      size: "0",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998566",
      type: "dir",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "folder",
      ext2: "folder",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: true,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103925",
      pid: "39227",
      name: "Folder 4",
      text: "Folder 4",
      size: "0",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998578",
      type: "dir",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "folder",
      ext2: "folder",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: true,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103914",
      pid: "39227",
      name: "Bugs Co-manage report by staff (4).xls",
      text: "Bugs Co-manage report by staff (4).xls",
      size: "1368",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607673423",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "xls",
      ext2: "xls",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103926",
      pid: "39227",
      name: "Bugs Co-manage report by staff.xls",
      text: "Bugs Co-manage report by staff.xls",
      size: "494080",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998678",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "xls",
      ext2: "xls",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103911",
      pid: "39227",
      name: "check.svg",
      text: "check.svg",
      size: "262",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607673420",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "default",
      ext2: "default",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103927",
      pid: "39227",
      name: "Component.zip",
      text: "Component.zip",
      size: "173273",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998679",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "zip",
      ext2: "zip",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103905",
      pid: "39227",
      name: "filter.svg",
      text: "filter.svg",
      size: "290",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607673417",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "default",
      ext2: "default",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103929",
      pid: "39227",
      name: "Project Xo\u0301a.pdf",
      text: "Project Xo\u0301a.pdf",
      size: "52488",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998737",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "pdf",
      ext2: "pdf",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103930",
      pid: "39227",
      name: "Screenshot_1.png",
      text: "Screenshot_1.png",
      size: "69274",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998888",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "png",
      ext2: "png",
      thumb: false,
      image: true,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103928",
      pid: "39227",
      name: "Video1606177746.980308.mov",
      text: "Video1606177746.980308.mov",
      size: "5592714",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607998711",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "default",
      ext2: "default",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
  ],
  access: {
    download: true,
    upload: true,
    edit: true,
    remove: true,
    read: true,
    share: true,
    guest: true,
  },
};

export const DATA_FOLDER_1 = {
  total: 5,
  files: [
    {
      id: "103931",
      pid: "103921",
      name: "Folder 1.1",
      text: "Folder 1.1",
      size: "24113",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999167",
      type: "dir",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "folder",
      ext2: "folder",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: true,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "3", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103934",
      pid: "103921",
      name: "Comanage 1.png",
      text: "Comanage 1.png",
      size: "132187",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999221",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "png",
      ext2: "png",
      thumb: false,
      image: true,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103932",
      pid: "103921",
      name: "Component.zip",
      text: "Component.zip",
      size: "173273",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999179",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "zip",
      ext2: "zip",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103933",
      pid: "103921",
      name: "edit-2.svg",
      text: "edit-2.svg",
      size: "291",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999198",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "default",
      ext2: "default",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103935",
      pid: "103921",
      name: "Project Xo\u0301a.pdf",
      text: "Project Xo\u0301a.pdf",
      size: "52488",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999234",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "pdf",
      ext2: "pdf",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: false,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
  ],
  access: {
    download: true,
    upload: true,
    edit: true,
    remove: true,
    read: true,
    share: true,
    guest: true,
  },
};

export const DATA_FOLDER_1_1 = {
  total: 3,
  files: [
    {
      id: "103937",
      pid: "103931",
      name: "report (1).docx",
      text: "report (1).docx",
      size: "8058",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999257",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "docx",
      ext2: "docx",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103936",
      pid: "103931",
      name: "report (2).docx",
      text: "report (2).docx",
      size: "8038",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999256",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "docx",
      ext2: "docx",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
    {
      id: "103938",
      pid: "103931",
      name: "report (3).docx",
      text: "report (3).docx",
      size: "8017",
      md5: "",
      author: "Thai3",
      authorId: "12285",
      rootUserId: "12285",
      regdate: "1607999258",
      type: "file",
      path: null,
      sync: false,
      star: false,
      notify: false,
      recover: null,
      lock: { status: false, user: false, username: null },
      share: false,
      company: "no",
      trash: false,
      ext: "docx",
      ext2: "docx",
      thumb: false,
      image: false,
      crypt: false,
      tag: null,
      desc: null,
      preview: true,
      access: {
        download: true,
        upload: false,
        edit: true,
        remove: true,
        read: true,
        share: true,
        guest: true,
      },
      count: { folder: "0", file: "0", memo: "0", history: "0" },
      flag: [""],
    },
  ],
  access: {
    download: true,
    upload: true,
    edit: true,
    remove: true,
    read: true,
    share: true,
    guest: true,
  },
};

export const DATA = {
  my: DATA_CLOUDDISK,
  103921: DATA_FOLDER_1,
  103931: DATA_FOLDER_1_1,
};
