// @ts-nocheck
export const SET_QUERY_PARAMS = "SET_QUERY_PARAMS"
export const SET_PERMIT_QUERY_PARAMS = "SET_PERMIT_QUERY_PARAMS"
export const IS_BACK_TO_LIST = "IS_BACK_TO_LIST"
export const SET_SEARCH_KEYWORK = "SET_SEARCH_KEYWORK"
export const TRIGGER_PRINT_MODAL = "TRIGGER_PRINT_MODAL"
