// @ts-nocheck
export const GET_CONFIG = "GET_CONFIG"
export const SET_GLOBAL_CONFIG = "SET_GLOBAL_CONFIG"
export const SET_USER_CONFIG = "SET_USER_CONFIG"
export const SET_PERSONAL_SETTING = "SET_PERSONAL_SETTING"
export const CLEAR_CONFIG = "CLEAR_CONFIG"
export const SAVE_MAIL_PERSONAL_SETTING = "SAVE_MAIL_PERSONAL_SETTING"
export const SET_MAIL_PERSONAL_SETTING = "SET_MAIL_PERSONAL_SETTING"
export const SET_ALL_CONFIG = "SET_ALL_CONFIG"