// @ts-nocheck
export const KEY_NAME_LANGUAGE_MENU = "menu"
export const KEY_NAME_LANGUAGE_SYSTEM = "system"
export const KEY_NAME_LANGUAGE_TYPE = "type"
export const KEY_NAME_LANGUAGE_KEY_LANG = "key_lang"

export const KEY_NAME_LANGUAGE_ENGLISH = "en"
export const KEY_NAME_LANGUAGE_VIETNAMESE = "vi"
export const KEY_NAME_LANGUAGE_KOREAN = "ko"
export const KEY_NAME_LANGUAGE_JAPAN = "jp"
export const KEY_NAME_LANGUAGE_CHINA_CH = "ch"
export const KEY_NAME_LANGUAGE_CHINA_ZH = "zh"
export const KEY_NAME_LANGUAGE_DEUTSCH = "de"
export const KEY_NAME_LANGUAGE_ESPANOL = "es"
export const KEY_NAME_LANGUAGE_INDONESIA = "id_code"
export const KEY_NAME_LANGUAGE_PORTUGUESE = "pt"
export const KEY_NAME_LANGUAGE_THAI = "th"
export const KEY_NAME_LANGUAGE_RUSSIAN = "ru"
export const KEY_NAME_LANGUAGE_DESCRIPTION = "description"
