// @ts-nocheck
export const dummy_data_lists = {
  isout: false,
  iscspam: false,
  canhack: true,
  newcount: 0,
  boxinfo: {
    mailbox: [
      {
        key: "Maildir",
        name: "H\u1ed9p th\u01b0 \u0111\u1ebfn",
        canshare: true,
        isshare: false,
        new: "0",
        total: "4",
        size: "0 Byte",
      },
      {
        key: "Storage",
        name: "Th\u01b0 l\u01b0u",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "Sent",
        name: "H\u1ed9p th\u01b0 \u0111i",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "External",
        name: "Th\u01b0 b\u00ean ngo\u00e0i",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "Temp",
        name: "Th\u01b0 nh\u00e1p",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "Spam",
        name: "Th\u01b0 r\u00e1c",
        canshare: false,
        isshare: false,
        spamlink: "",
        new: "0",
        total: "0",
        isspamlink: "n",
        size: "0 Byte",
      },
      {
        key: "Trash",
        name: "R\u00e1c",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
    ],
  },
  shareing: false,
  shareinfo: {},
  myeamil: "anhduy@global.hanbiro.com",
  hasspammanager: true,
  maillist: [
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test sending email 4",
      spaminfo: {},
      addr: "Anh Duy <anhduy@hanbiro.vn>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685931472.1859687",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2237,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "2ca86866-0347-11ee-a4f3-0cc47a7a43da",
      from_name: "Anh Duy",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685931472.1859687",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test sending email 4",
      is_file: 0,
      date: "06/05 11:17",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1686014818.09_31873",
      from_addr: "anhduy@hanbiro.vn",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "",
      htime: "",
      "message-id": "20230605021745.23569.72058@gvn5.hanbiro.net",
      page: 1,
      block: 15,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test sending email 3",
      spaminfo: {},
      addr: "Anh Duy <anhduy@hanbiro.vn>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685691862.847950",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2249,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "4a5cf20c-0119-11ee-b10b-0cc47a7a43da",
      from_name: "Anh Duy",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685691862.847950",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test sending email 3",
      is_file: 0,
      date: "06/02 16:44",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1686014818.09_41393",
      from_addr: "anhduy@hanbiro.vn",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "",
      htime: "",
      "message-id": "20230602074416.38228.21531@gvn5.hanbiro.net",
      page: 1,
      block: 15,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test sending email 2",
      spaminfo: {},
      addr: "Anh Duy <anhduy@hanbiro.vn>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685691798.840760",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2248,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "24363930-0119-11ee-8b4b-0cc47a7a43da",
      from_name: "Anh Duy",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685691798.840760",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test sending email 2",
      is_file: 0,
      date: "06/02 16:43",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1686014818.09_71363",
      from_addr: "anhduy@hanbiro.vn",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "",
      htime: "",
      "message-id": "20230602074312.97316.31952@gvn5.hanbiro.net",
      page: 1,
      block: 15,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test sending email",
      spaminfo: {},
      addr: "Anh Duy <anhduy@hanbiro.vn>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685681148.3925736",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2240,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "580ccce8-0100-11ee-bfd6-0cc47a7a43da",
      from_name: "Anh Duy",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685681148.3925736",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test sending email",
      is_file: 0,
      date: "06/02 13:45",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1686014818.09_94536",
      from_addr: "anhduy@hanbiro.vn",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "",
      htime: "",
      "message-id": "20230602044541.32793.91674@gvn5.hanbiro.net",
      page: 1,
      block: 15,
    },
  ],
  boxname: "H\u1ed9p th\u01b0 \u0111\u1ebfn",
  sentdelay: 0,
  set_start: 15,
  isshare: false,
  emllimit: 50,
  total: 4,
  searchmsg: "",
  boxid: "Maildir",
}
