// @ts-nocheck
export const dummy_data_detail = [
  {
    "1685931472.1859687": {
      mailview: [
        {
          cloudlist: [],
          shareing: false,
          cc: "",
          canshare: true,
          hasspammanager: true,
          nextmail: "",
          sentdelay: 0,
          file: [],
          approval: {},
          fileinfo: {},
          bcc: "",
          contents:
            '<div checkbox-data="%7B%7D" uniq="1685931437808" style="font-family: verdana, geneva; font-size: 12pt;"><div style="font-family: \'MS PGothic\',verdana,arial; font-size: 9pt;" MS PGothic\',verdana,arial; font-size: 9pt;">Sending email 1234</div></div>\n<table name="Hanbiro_Groupware_Acknowledgment" style="display:none"><tr><td><img src="https://gw.hanbiro.vn/email/receiveCheck?q=YW5oZHV5fGhhbmJpcm8udm58MTY4NTkzMTQ2NS4yOTUxNDZ8ZGI%3D" border="0"></td></tr></table>',
          subject: "Test sending email 4",
          from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
          isaddropen: true,
          tmpname: "",
          prenextinfo: {
            nextinfo: {},
            preinfo: {
              sigmsg: "S",
              timeuuid: "4a5cf20c-0119-11ee-b10b-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2249",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685691862.847950",
              date: "2023/06/02 14:44:22",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230602074416.38228.21531@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email 3",
            },
          },
          isimportant: false,
          isent: false,
          receive_data: {},
          issimplemode: false,
          receivedate: "2023/06/05 11:17:52",
          timeuuid: "2ca86866-0347-11ee-a4f3-0cc47a7a43da",
          to: "anhduy@global.hanbiro.com",
          isallremove: "N",
          security_info: {
            isspoofmail: {
              sender: "",
              similar: 0.0,
              target: "",
              result: false,
            },
            isbayesian: { reason: "0", usemanagerdb: false, result: false },
            isspf: { senddomain: "", result: false },
            isencrypt: { result: true },
            isspicious: { reason: "", result: false },
            isvirus: { reason: "", result: false },
            isrbl: { reason: "", result: false },
          },
          shareinfo: {},
          isnotsave: false,
          myeamil: "anhduy@global.hanbiro.com",
          stripcontents: "Sending email 1234",
          ical: {},
          remoteip: "42.117.3.148",
          isshare: false,
          sendlater: {
            issendlater: false,
            sendlater_timezone: "",
            sendlater_regtime: "",
            sendlater_status: "",
          },
          secumode: "0",
          prevmail: "1685691862.847950",
          acl: "Maildir",
          isapproval: false,
          canhack: true,
          geoip: {
            country_code3: "vn",
            country_name: "Vietnam",
            isprivate: false,
            time_zone: "Asia/Ho_Chi_Minh",
            country_code: "vn",
          },
          groupuse: "N",
        },
      ],
    },
  },
  {
    "1685691862.847950": {
      mailview: [
        {
          cloudlist: [],
          shareing: false,
          cc: "",
          canshare: true,
          hasspammanager: true,
          nextmail: "1685931472.1859687",
          sentdelay: 0,
          file: [],
          approval: {},
          fileinfo: {},
          bcc: "",
          contents:
            '<div checkbox-data="%7B%7D" uniq="1685691835713" style="font-family: verdana, geneva; font-size: 12pt;"><div style="font-family: \'MS PGothic\',verdana,arial; font-size: 9pt;" MS PGothic\',verdana,arial; font-size: 9pt;">Test sending email 3</div></div>\n<table name="Hanbiro_Groupware_Acknowledgment" style="display:none"><tr><td><img src="https://gw.hanbiro.vn/email/receiveCheck?q=YW5oZHV5fGhhbmJpcm8udm58MTY4NTY5MTg1Ni4wMjc5NTZ8ZGI%3D" border="0"></td></tr></table>',
          subject: "Test sending email 3",
          from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
          isaddropen: true,
          tmpname: "",
          prenextinfo: {
            nextinfo: {
              sigmsg: "S",
              timeuuid: "2ca86866-0347-11ee-a4f3-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2237",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685931472.1859687",
              date: "2023/06/05 11:17:52",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230605021745.23569.72058@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email 4",
            },
            preinfo: {
              sigmsg: "S",
              timeuuid: "24363930-0119-11ee-8b4b-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2248",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685691798.840760",
              date: "2023/06/02 16:43:18",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230602074312.97316.31952@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email 2",
            },
          },
          isimportant: false,
          isent: false,
          receive_data: {},
          issimplemode: false,
          receivedate: "2023/06/02 16:44:22",
          timeuuid: "4a5cf20c-0119-11ee-b10b-0cc47a7a43da",
          to: "anhduy@global.hanbiro.com",
          isallremove: "N",
          security_info: {
            isspoofmail: {
              sender: "",
              similar: 0.0,
              target: "",
              result: false,
            },
            isbayesian: { reason: "0", usemanagerdb: false, result: false },
            isspf: { senddomain: "", result: false },
            isencrypt: { result: true },
            isspicious: { reason: "", result: false },
            isvirus: { reason: "", result: false },
            isrbl: { reason: "", result: false },
          },
          shareinfo: {},
          isnotsave: false,
          myeamil: "anhduy@global.hanbiro.com",
          stripcontents: "Test sending email 3",
          ical: {},
          remoteip: "42.117.3.148",
          isshare: false,
          sendlater: {
            issendlater: false,
            sendlater_timezone: "",
            sendlater_regtime: "",
            sendlater_status: "",
          },
          secumode: "0",
          prevmail: "1685691798.840760",
          acl: "Maildir",
          isapproval: false,
          canhack: true,
          geoip: {
            country_code3: "vn",
            country_name: "Vietnam",
            isprivate: false,
            time_zone: "Asia/Ho_Chi_Minh",
            country_code: "vn",
          },
          groupuse: "N",
        },
      ],
    },
  },
  {
    "1685691798.840760": {
      mailview: [
        {
          cloudlist: [],
          shareing: false,
          cc: "",
          canshare: true,
          hasspammanager: true,
          nextmail: "1685691862.847950",
          sentdelay: 0,
          file: [],
          approval: {},
          fileinfo: {},
          bcc: "",
          contents:
            '<div checkbox-data="%7B%7D" uniq="1685691757252" style="font-family: verdana, geneva; font-size: 12pt;"><div style="font-family: \'MS PGothic\',verdana,arial; font-size: 9pt;" MS PGothic\',verdana,arial; font-size: 9pt;">Test sending email 2</div></div>\n<table name="Hanbiro_Groupware_Acknowledgment" style="display:none"><tr><td><img src="https://gw.hanbiro.vn/email/receiveCheck?q=YW5oZHV5fGhhbmJpcm8udm58MTY4NTY5MTc5Mi4zNTg5NDd8ZGI%3D" border="0"></td></tr></table>',
          subject: "Test sending email 2",
          from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
          isaddropen: true,
          tmpname: "",
          prenextinfo: {
            nextinfo: {
              sigmsg: "S",
              timeuuid: "4a5cf20c-0119-11ee-b10b-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2249",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685691862.847950",
              date: "2023/06/02 14:44:22",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230602074416.38228.21531@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email 3",
            },
            preinfo: {
              sigmsg: "S",
              timeuuid: "580ccce8-0100-11ee-bfd6-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2240",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685681148.3925736",
              date: "2023/06/02 11:45:48",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230602044541.32793.91674@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email",
            },
          },
          isimportant: false,
          isent: false,
          receive_data: {},
          issimplemode: false,
          receivedate: "2023/06/02 16:43:18",
          timeuuid: "24363930-0119-11ee-8b4b-0cc47a7a43da",
          to: "anhduy@global.hanbiro.com",
          isallremove: "N",
          security_info: {
            isspoofmail: {
              sender: "",
              similar: 0.0,
              target: "",
              result: false,
            },
            isbayesian: { reason: "0", usemanagerdb: false, result: false },
            isspf: { senddomain: "", result: false },
            isencrypt: { result: true },
            isspicious: { reason: "", result: false },
            isvirus: { reason: "", result: false },
            isrbl: { reason: "", result: false },
          },
          shareinfo: {},
          isnotsave: false,
          myeamil: "anhduy@global.hanbiro.com",
          stripcontents: "Test sending email 2",
          ical: {},
          remoteip: "42.117.3.148",
          isshare: false,
          sendlater: {
            issendlater: false,
            sendlater_timezone: "",
            sendlater_regtime: "",
            sendlater_status: "",
          },
          secumode: "0",
          prevmail: "1685681148.3925736",
          acl: "Maildir",
          isapproval: false,
          canhack: true,
          geoip: {
            country_code3: "vn",
            country_name: "Vietnam",
            isprivate: false,
            time_zone: "Asia/Ho_Chi_Minh",
            country_code: "vn",
          },
          groupuse: "N",
        },
      ],
    },
  },
  {
    1685681148.3925736: {
      mailview: [
        {
          cloudlist: [],
          shareing: false,
          cc: "",
          canshare: true,
          hasspammanager: true,
          nextmail: "1685691798.840760",
          sentdelay: 0,
          file: [],
          approval: {},
          fileinfo: {},
          bcc: "",
          contents:
            '<div checkbox-data="%7B%7D" uniq="1685681085360" style="font-family: verdana, geneva; font-size: 12pt;"><div style="font-family: \'MS PGothic\',verdana,arial; font-size: 9pt;" MS PGothic\',verdana,arial; font-size: 9pt;">Test sending email</div></div>\n<table name="Hanbiro_Groupware_Acknowledgment" style="display:none"><tr><td><img src="https://gw.hanbiro.vn/email/receiveCheck?q=YW5oZHV5fGhhbmJpcm8udm58MTY4NTY4MTE0MS45MTQwNjd8ZGI%3D" border="0"></td></tr></table>',
          subject: "Test sending email",
          from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
          isaddropen: true,
          tmpname: "",
          prenextinfo: {
            nextinfo: {
              sigmsg: "S",
              timeuuid: "24363930-0119-11ee-8b4b-0cc47a7a43da",
              from: '"Anh Duy" &lt;anhduy@hanbiro.vn&gt;',
              header: "",
              i: 0,
              size: "2248",
              groupcount: 0,
              isgroup: "no",
              mailbox: "Maildir",
              to: "anhduy@global.hanbiro.com",
              namefile: "1685691798.840760",
              date: "2023/06/02 14:43:18",
              cloudchk: "0",
              vsstatus: "spam,False",
              "message-id": "20230602074312.97316.31952@gvn5.hanbiro.net",
              isfile: 0,
              subject: "Test sending email 2",
            },
            preinfo: {},
          },
          isimportant: false,
          isent: false,
          receive_data: {},
          issimplemode: false,
          receivedate: "2023/06/02 13:45:48",
          timeuuid: "580ccce8-0100-11ee-bfd6-0cc47a7a43da",
          to: "anhduy@global.hanbiro.com",
          isallremove: "N",
          security_info: {
            isspoofmail: {
              sender: "",
              similar: 0.0,
              target: "",
              result: false,
            },
            isbayesian: { reason: "0", usemanagerdb: false, result: false },
            isspf: { senddomain: "", result: false },
            isencrypt: { result: true },
            isspicious: { reason: "", result: false },
            isvirus: { reason: "", result: false },
            isrbl: { reason: "", result: false },
          },
          shareinfo: {},
          isnotsave: false,
          myeamil: "anhduy@global.hanbiro.com",
          stripcontents: "Test sending email",
          ical: {},
          remoteip: "42.117.3.148",
          isshare: false,
          sendlater: {
            issendlater: false,
            sendlater_timezone: "",
            sendlater_regtime: "",
            sendlater_status: "",
          },
          secumode: "0",
          prevmail: "",
          acl: "Maildir",
          isapproval: false,
          canhack: true,
          geoip: {
            country_code3: "vn",
            country_name: "Vietnam",
            isprivate: false,
            time_zone: "Asia/Ho_Chi_Minh",
            country_code: "vn",
          },
          groupuse: "N",
        },
      ],
    },
  },
]
