// @ts-nocheck
const listResponse = {
  isout: false,
  iscspam: false,
  canhack: true,
  newcount: 195,
  boxinfo: {
    mailbox: [
      {
        key: "Maildir",
        name: "Inbox",
        canshare: true,
        isshare: false,
        new: "91",
        total: "207",
        size: "0 Byte",
      },
      {
        key: "Storage",
        name: "Mail Archive",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "Sent",
        name: "Sent Mail",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "External",
        name: "Fetching Mail",
        canshare: true,
        isshare: false,
        new: "0",
        total: "0",
        size: "0 Byte",
      },
      {
        key: "Temp",
        name: "Drafts",
        canshare: true,
        isshare: false,
        new: "0",
        total: "4",
        size: "0 Byte",
      },
      {
        key: "Spam",
        name: "Spam",
        canshare: false,
        isshare: false,
        spamlink: "",
        new: "0",
        total: "8",
        isspamlink: "n",
        size: "0 Byte",
      },
      {
        key: "Trash",
        name: "Trash",
        canshare: true,
        isshare: false,
        new: "24",
        total: "57",
        size: "0 Byte",
      },
      {
        key: "Archives",
        name: "archive",
        canshare: false,
        isshare: false,
        new: "0",
        total: "0",
      },
      {
        key: "1665567197.44",
        name: "Editor - remove link",
        canshare: true,
        isshare: false,
        new: "0",
        total: "2",
      },
      {
        key: "1632897714.15",
        name: "PT5 210929",
        canshare: true,
        isshare: true,
        new: "1",
        total: "5",
      },
      {
        key: "1665567194.95",
        name: "\ubcf4\ub0b8\uba54\uc77c",
        canshare: true,
        isshare: false,
        new: "0",
        total: "1",
      },
      {
        key: "1638348862.77",
        name: "Error editor",
        canshare: true,
        isshare: false,
        new: "0",
        total: "14",
      },
      {
        key: "1665567610.56",
        name: "\ubcf4\ub0b4\uba54\uc77c",
        canshare: true,
        isshare: false,
        new: "0",
        total: "2",
      },
    ],
  },
  shareing: false,
  shareinfo: {},
  myeamil: "phuctest5@global3.hanbiro.com",
  hasspammanager: true,
  maillist: [
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject:
        "GUAM JOA CONFIRMED Skydive Guam on Wednesday, January 4 2023 @ 8:00am - 11:00am",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685608967.486194",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 3628,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "48e08d74-0058-11ee-bc6f-0cc47a7a43da",
      from_name: "phuctest5",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685608967.486194",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 1,
      date: "06/01 11:42",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.04_95735",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "Inbox",
      htime: "",
      "message-id": "20230601084244.21707.95647@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject:
        "FW: [현대엔지니어링] 협력업체 AS상시평가 결과 안내 (2023-05-12일 기준)",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685608964.184063",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 3162,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "46e8aff6-0058-11ee-85bf-0cc47a7a43da",
      from_name: "",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685608964.184063",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 1,
      date: "06/01 11:42",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.04_81924",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230601084244.21707.95647@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject:
        "lamvt5 nick name 2023-05-22(09:00 ~ 10:00) Annual vacation (gw.hanbiro.vn)",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685515654.3220001",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1727,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "05e5a922-ff7f-11ed-bbab-0cc47a7a43da",
      from_name: "phuctest5",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685515654.3220001",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 0,
      date: "05/31 09:47",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.04_46304",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "Inbox",
      htime: "",
      "message-id": "20230531064732.86843.38079@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject:
        "[잘되려나?? 될거임....!@#$!@#$!@#$_R] Test mail 8 [phuctest5@global3.hanbiro.com → ptest220404@global.hanbiro.com]",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685515652.960537",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1259,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "0515eaf8-ff7f-11ed-b0d4-0cc47a7a43da",
      from_name: "Anh, Phuctest5",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685515652.960537",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 0,
      date: "05/31 09:47",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_45533",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230531064732.86843.38079@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject:
        "[잘되려나?? 될거임....!@#$!@#$!@#$_S] [잘되려나?? 될거임....!@#$!@#$!@#$_R] [Email Error] 메일발송실패 [root@global3.hanbiro.com → xemxem@global.hanbiro.com] [phuc@global.hanbiro.com → hphuc@vndev.hanbiro.com]",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685508182.2426289",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 4546,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "a030d4b0-ff6d-11ed-af8b-0cc47a7a43da",
      from_name: "phuctest5",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685508182.2426289",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 1,
      date: "05/31 07:43",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_78970",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "Inbox",
      htime: "",
      "message-id": "20230531044259.39423.90197@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685508179.361594",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 4074,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "9e793842-ff6d-11ed-ae2b-0cc47a7a43da",
      from_name: "",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685508179.361594",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 1,
      date: "05/31 07:42",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_52116",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230531044259.39423.90197@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "TestTest",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685507617.2365010",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 4023,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "4f6bbcd2-ff6c-11ed-8afa-0cc47a7a43da",
      from_name: "phuctest5",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685507617.2365010",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "TestTest",
      is_file: 1,
      date: "05/31 07:33",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_70368",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "Inbox",
      htime: "",
      "message-id": "20230531043336.97445.30297@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "TestTest",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685507616.268537",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 3551,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "4ed809ba-ff6c-11ed-9e26-0cc47a7a43da",
      from_name: "",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685507616.268537",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "TestTest",
      is_file: 1,
      date: "05/31 07:33",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_93958",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230531043336.97445.30297@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "RE: [External] - RE: Revise AK Vina Quats Q2'23 allocation",
      spaminfo: {},
      addr: "Nguy\u1ec5n B\u00e1 \u0110\u1ee9c <duckevin_sales@akvina.vn>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685504273.2316",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 711233,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "863d1562-ff64-11ed-817d-0cc47a7a43da",
      from_name: "Nguy\u1ec5n B\u00e1 \u0110\u1ee9c",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685504273.2316",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject:
        "RE: [External] - RE: Revise AK Vina Quats Q2'23 allocation",
      is_file: 0,
      date: "05/31 06:37",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_76572",
      from_addr: "duckevin_sales@akvina.vn",
      sigmsg: 1,
      acl: "1638348862.77",
      secu_state: "",
      boxname: "Error editor",
      htime: "",
      "message-id": "20230531033753.74629.73635@gvn8.hanbiro.net",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "FW: 2023.05.31 \uc678\ud654\uc785\uae08 ( UNITEC $ 178,600 )",
      spaminfo: {},
      addr: "\uad8c\ub098\ud604(nhkwon) <nhkwon@dmcmt.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685501575.5347",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 256935,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "3e493438-ff5e-11ed-9268-0cc47a7a43da",
      from_name: "\uad8c\ub098\ud604(nhkwon)",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685501575.5347",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject:
        "FW: 2023.05.31 \uc678\ud654\uc785\uae08 ( UNITEC $ 178,600 )",
      is_file: 1,
      date: "05/31 05:52",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.05_9402",
      from_addr: "nhkwon@dmcmt.com",
      sigmsg: 1,
      acl: "1665567610.56",
      secu_state: "",
      boxname: "\ubcf4\ub0b4\uba54\uc77c",
      htime: "",
      "message-id": "20230531025254.38515.99082@gw.dmcmt.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685070487.2436638",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2079,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "89a4339e-fb72-11ed-94ec-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685070487.2436638",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 06:08",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_49415",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "64702296f0a38@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685066580.2026498",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2079,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "70dd0e02-fb69-11ed-a9ca-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685066580.2026498",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 05:03",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_11424",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "6470135422307@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685066357.2002811",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2094,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "ebf197fa-fb68-11ed-8d82-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685066357.2002811",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 04:59",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_42844",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "6470127505e7f@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685066222.1989562",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1957,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "9b7a06ba-fb68-11ed-a996-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685066222.1989562",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 04:57",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_45655",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "647011edaa633@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685065652.1927161",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1999,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "47b9f9f8-fb67-11ed-a946-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685065652.1927161",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 04:47",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_93974",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "64700fb42d3e1@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Sprint Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685065535.1914302",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1978,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "01fcff3e-fb67-11ed-ad9e-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685065535.1914302",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Sprint Notice",
      is_file: 0,
      date: "05/26 04:45",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_15093",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "64700f3f50497@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Print Notice",
      spaminfo: {},
      addr: "No Reply <noreply@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685007774.4190175",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 1977,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "85e292de-fae0-11ed-b386-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685007774.4190175",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Print Notice",
      is_file: 0,
      date: "05/25 12:42",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_89829",
      from_addr: "noreply@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "646f2d9db0319@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "ACFG",
      spaminfo: {},
      addr: "No Reply <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685007743.4187125",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 955,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "73684d76-fae0-11ed-a8bf-0cc47a7a43da",
      from_name: "No Reply",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685007743.4187125",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "ACFG",
      is_file: 0,
      date: "05/25 12:42",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_71589",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Trash",
      secu_state: "",
      boxname: "Trash",
      htime: "",
      "message-id": "646f2d7ecfa60@global3.hanbiro.com",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "phuctest5's Project(PT230525 Scrum) Work Notice",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685007576.869702",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 3551,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "1022f0be-fae0-11ed-85a3-0cc47a7a43da",
      from_name: "",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685007576.869702",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "phuctest5's Project(PT230525 Scrum) Work Notice",
      is_file: 0,
      date: "05/25 12:39",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_41956",
      from_addr: "phuctest@global.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230525093936.68897.11444@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685007474.4157737",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2625,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "d311b628-fadf-11ed-a1c8-0cc47a7a43da",
      from_name: "phuctest5",
      isnew: 0,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685007474.4157737",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 0,
      date: "05/25 12:37",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.06_43079",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 1,
      acl: "Maildir",
      secu_state: "",
      boxname: "Inbox",
      htime: "",
      "message-id": "20230525093752.19971.73514@dcnode2",
      page: 1,
      block: 25,
    },
    {
      sentsecuinfo: {},
      canshare: true,
      isbmail: false,
      ispreview: false,
      subject: "Test",
      spaminfo: {},
      addr: "phuctest5 <phuctest5@global3.hanbiro.com>",
      deluser: "",
      secu_approvaluser: "",
      groupcount: 0,
      mid: "1685007472.398052",
      delay: "no",
      start: 0,
      getbackstate: "",
      isimportant: false,
      size: 2153,
      secu_approvaltime: "",
      secu_reason: "",
      timeuuid: "d1ddd4e8-fadf-11ed-9267-0cc47a7a43da",
      from_name: "",
      isnew: 1,
      security_info: {
        isspoofmail: {},
        isbayesian: {},
        hasinfo: false,
        isspf: {},
        isencrypt: {},
        isspicious: {},
        isvirus: {},
        isrbl: {},
      },
      timestamp: "1685007472.398052",
      isnotsave: false,
      vsstatus: "",
      sharedid: "",
      stripsubject: "Test",
      is_file: 0,
      date: "05/25 12:37",
      sendlater: {
        issendlater: false,
        sendlater_timezone: "",
        sendlater_regtime: "",
        sendlater_status: "",
      },
      basicBlock: "100",
      getbackstr: "",
      dummy: "1685936428.07_1397",
      from_addr: "phuctest5@global3.hanbiro.com",
      sigmsg: 0,
      acl: "Sent",
      secu_state: "",
      boxname: "Sent Mail",
      htime: "",
      "message-id": "20230525093752.19971.73514@dcnode2",
      page: 1,
      block: 25,
    },
  ],
  boxname: "",
  sentdelay: 0,
  set_start: 25,
  isshare: false,
  emllimit: 50,
  total: 439,
  searchmsg: "",
  boxid: "all",
}

export { listResponse }
