// @ts-nocheck
export const SET_SOCKET_COUNT = "SET_SOCKET_COUNT"
export const SET_SOCKET_DATA = "SET_SOCKET_DATA"
export const SET_SIDEBAR_COUNT = "SET_SIDEBAR_COUNT"
export const SET_SOCKET_MENU_DATA = "SET_SOCKET_MENU_DATA"
export const SET_SIDEBAR_FOLDER_KEYWORD = "SET_SIDEBAR_FOLDER_KEYWORD"
