// @ts-nocheck
export const OPEN_COMPOSE_MAIL = "OPEN_COMPOSE_MAIL"
export const CLOSE_COMPOSE_MAIL = "CLOSE_COMPOSE_MAIL"
export const OPEN_ORG_MODAL = "OPEN_ORG_MODAL"
export const CLOSE_ORG_MODAL = "CLOSE_ORG_MODAL"
export const EXPAND_COMPOSE_MODAL = "EXPAND_COMPOSE_MODAL"
export const UPDATE_COMPOSE_DATA = "UPDATE_COMPOSE_DATA"
export const FORCE_UPDATE_COMPOSE_DATA = "FORCE_UPDATE_COMPOSE_DATA"
export const UPDATE_LOCAL_COMPOSE_MODE = "UPDATE_LOCAL_COMPOSE_MODE"
